version: '3.8'
services:
  prod:
    container_name: dev
    build:
      context: .
      dockerfile: Dockerfile-nc
    ports:
      - '80:80'
    environment:
      - NODE_ENV=production
      - APP=nocc

